# Generated by Django 4.2.2 on 2023-06-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('id',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='title',
        ),
    ]
