# Generated by Django 4.2.2 on 2023-07-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_productimages_delete_productpictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='freeDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
