# Generated by Django 4.2.2 on 2023-07-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_product_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='store_api.sale'),
        ),
    ]
