# Generated by Django 4.2.2 on 2023-07-23 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_sale_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_api.sale'),
        ),
    ]
