# Generated by Django 4.2.2 on 2023-07-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_tag_producttags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='store_api.tag'),
        ),
        migrations.DeleteModel(
            name='ProductTags',
        ),
    ]
