# Generated by Django 4.2.2 on 2023-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0006_productspecifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecifications',
            options={'verbose_name': 'Specification'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='added_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
