# Generated by Django 4.1.5 on 2023-02-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='product_pictures/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.product')),
            ],
        ),
    ]
