# Generated by Django 4.1.5 on 2023-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_product_limited_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rate',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
