# Generated by Django 4.1.5 on 2023-02-14 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_productpictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
