# Generated by Django 4.1.5 on 2023-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_feedback_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_pictures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
