# Generated by Django 4.1.5 on 2023-03-12 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_store', '0004_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='UserCart',
        ),
    ]
