# Generated by Django 4.1.5 on 2023-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0002_paymenttransactions_satisfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactions',
            name='account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransactions',
            name='summ',
            field=models.FloatField(null=True),
        ),
    ]
